on: [pull_request]

name: breaking

jobs:
  validate-protos:
    name: buf breaking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-setup-action@v1.28.1
        with:
            github_token: ${{ github.token }}
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: 'https://github.com/canardleteer/grpc-service-rs.git#branch=main,subdir=proto'
          input: proto