on: [push, pull_request]

name: Lint

jobs:
  buf-lint:
    name: buf lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: proto

  cargo-check:
    name: cargo check
    strategy:
      matrix:
        working_dir: [client, service]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          args: --manifest-path ${{ matrix.working_dir }}/Cargo.toml
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ${{ matrix.working_dir }}/Cargo.toml

  cargo-fmt:
    name: cargo fmt
    strategy:
      matrix:
        working_dir: [client, service]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path ${{ matrix.working_dir }}/Cargo.toml -- --check

  cargo-clippy:
    name: cargo clippy
    strategy:
      matrix:
        working_dir: [client, service]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ${{ matrix.working_dir }}/Cargo.toml -- -D warnings
